### ISSUE TITLE
Upload by URL

### ISSUE THREAD

**Issue by highri5e** [ZeroCho/react-filestack#125]
lib version: 4.0.0

When trying to upload by URL the error appears.

In Chrome:

`
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at picker.js:1:185032
    at Uo.resizeImage (picker.js:1:186284)
    at Array.<anonymous> (picker.js:1:90281)
    at Uo.dispatch (picker.js:1:91997)
    at Uo.dispatch (picker.js:1:86009)
    at Image.i.onload (picker.js:1:184839)
`

In Firefox the error message is more descriptive: 

`Uncaught TypeError: can't access property "split", e.name is undefined`

Tried multiple images of different sizes.

one of images: https://www.stonemarket.co.uk/assets/images/garden-designer/rosemary-coldstream-garden-design_st-albans_402_k31528_gl.jpg

**Comment by megantaylor** [comment]
also running into this issue, seems related to https://github.com/filestack/filestack-js/issues/495
